#!/bin/bash
# 真实文章生成器（调用 OpenClaw agent）- 多语言版本

set -e

SITE_DIR="$HOME/openclaw-site"
EN_POST_DIR="$SITE_DIR/content/en/posts"
ZH_POST_DIR="$SITE_DIR/content/zh/posts"
mkdir -p "$EN_POST_DIR" "$ZH_POST_DIR"

# 随机选择一个主题
TOPICS_FILE="$SITE_DIR/topics.txt"
if [ -f "$TOPICS_FILE" ]; then
    TOPIC=$(shuf -n1 "$TOPICS_FILE")
else
    TOPIC="人工智能与未来生活"
fi

DATE=$(date +%Y-%m-%d)
SLUG="post-$(date +%Y%m%d%H%M%S)"
EN_FILENAME="$EN_POST_DIR/$DATE-$SLUG.md"
ZH_FILENAME="$ZH_POST_DIR/$DATE-$SLUG.md"

echo "🤖 正在让明鉴生成文章，主题：$TOPIC" >&2

# 调用 OpenClaw agent 生成英文文章
EN_PROMPT="请以专业、易懂的英文风格写一篇关于《${TOPIC}》的原创文章，字数约800字。请按以下格式输出：
第一行：文章标题（不要加#）
正文内容（Markdown格式，自然分段）
最后一行：Keywords: word1,word2,word3

要求：
1. 标题要吸引人且专业
2. 内容要有深度和技术准确性
3. 使用适当的Markdown格式
4. 关键词要相关且有用"

echo "生成英文文章..." >&2
EN_CONTENT=$(openclaw agent --agent main --message "$EN_PROMPT" 2>/dev/null)

# 提取英文标题（第一行）
EN_TITLE=$(echo "$EN_CONTENT" | head -n1 | sed 's/^#* *//')

# 提取英文正文（去掉第一行和最后一行）
EN_BODY=$(echo "$EN_CONTENT" | tail -n +2 | head -n -1)

# 提取英文关键词（最后一行）
EN_KEYWORDS=$(echo "$EN_CONTENT" | tail -n1 | sed 's/Keywords: //')

# 若提取失败，使用默认值
[ -z "$EN_TITLE" ] && EN_TITLE="Daily Thoughts: $TOPIC"
[ -z "$EN_KEYWORDS" ] && EN_KEYWORDS="$TOPIC,AI,Technology"

# 生成中文主题（基于英文主题）
ZH_TOPIC_PROMPT="请将以下英文技术主题翻译成中文：'$TOPIC'。只返回中文翻译，不要其他内容。"
ZH_TOPIC=$(openclaw agent --agent main --message "$ZH_TOPIC_PROMPT" 2>/dev/null)
[ -z "$ZH_TOPIC" ] && ZH_TOPIC="$TOPIC"

# 生成中文标题
ZH_TITLE_PROMPT="请将以下英文文章标题翻译成中文：'$EN_TITLE'。只返回中文翻译，不要其他内容。"
ZH_TITLE=$(openclaw agent --agent main --message "$ZH_TITLE_PROMPT" 2>/dev/null)
[ -z "$ZH_TITLE" ] && ZH_TITLE="$EN_TITLE"

# 生成中文文章
ZH_PROMPT="请将以下英文文章翻译成中文，保持专业性和技术准确性：

$EN_BODY

要求：
1. 准确翻译技术内容
2. 保持专业术语的一致性
3. 适应中文读者的阅读习惯
4. 保持相同的结构和格式"

echo "生成中文文章..." >&2
ZH_BODY=$(openclaw agent --agent main --message "$ZH_PROMPT" 2>/dev/null)
[ -z "$ZH_BODY" ] && ZH_BODY="$EN_BODY"

# 生成中文关键词
ZH_KEYWORDS_PROMPT="请将以下英文关键词翻译成中文：'$EN_KEYWORDS'。格式：关键词1,关键词2,关键词3"
ZH_KEYWORDS=$(openclaw agent --agent main --message "$ZH_KEYWORDS_PROMPT" 2>/dev/null)
[ -z "$ZH_KEYWORDS" ] && ZH_KEYWORDS="$EN_KEYWORDS"

# 写入英文Markdown文件
cat > "$EN_FILENAME" << EOF
---
title: "$EN_TITLE"
date: $DATE
draft: false
tags: [${EN_KEYWORDS//,/, }]
categories: ["Technology"]
keywords: "$EN_KEYWORDS"
description: "$EN_TITLE"
---

$EN_BODY

---

*This article was automatically generated by Mingjian 🦞 to explore topics related to $TOPIC.*
EOF

echo "✅ 英文文章已生成：$EN_FILENAME" >&2

# 写入中文Markdown文件
cat > "$ZH_FILENAME" << EOF
---
title: "$ZH_TITLE"
date: $DATE
draft: false
tags: [${ZH_KEYWORDS//,/, }]
categories: ["技术"]
keywords: "$ZH_KEYWORDS"
description: "$ZH_TITLE"
---

$ZH_BODY

---

*本文由明鉴 🦞 自动生成，旨在探讨 $ZH_TOPIC 的相关话题。*
EOF

echo "✅ 中文文章已生成：$ZH_FILENAME" >&2

echo "📊 生成统计："
echo "   英文文章: $EN_TITLE"
echo "   文件位置: $EN_FILENAME"
echo "   中文文章: $ZH_TITLE"
echo "   文件位置: $ZH_FILENAME"
echo ""
echo "🚀 下一步：运行部署脚本"
echo "   bash $SITE_DIR/deploy_to_github_pages.sh"